//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nyivantarto
{
    using System;
    using System.Collections.Generic;
    
    public partial class FizetesMod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FizetesMod()
        {
            this.Megrendeles = new HashSet<Megrendeles>();
        }
    
        public int ID { get; set; }
        public string Mod { get; set; }
        public Nullable<int> Hatarido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Megrendeles> Megrendeles { get; set; }
    }
}
