//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nyivantarto
{
    using System;
    using System.Collections.Generic;
    
    public partial class MegrendelesTetel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MegrendelesTetel()
        {
            this.SzamlaTetel = new HashSet<SzamlaTetel>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Mennyiseg { get; set; }
        public Nullable<double> NettoAr { get; set; }
        public Nullable<int> MegrendelesID { get; set; }
        public Nullable<int> TermekID { get; set; }
        public Nullable<int> StatuszID { get; set; }
    
        public virtual Megrendeles Megrendeles { get; set; }
        public virtual Statusz Statusz { get; set; }
        public virtual Termek Termek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SzamlaTetel> SzamlaTetel { get; set; }
    }
}
