//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nyivantarto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TALXCEEntities : DbContext
    {
        public TALXCEEntities()
            : base("name=TALXCEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AFA> AFA { get; set; }
        public virtual DbSet<FizetesMod> FizetesMod { get; set; }
        public virtual DbSet<Kategoria> Kategoria { get; set; }
        public virtual DbSet<Megrendeles> Megrendeles { get; set; }
        public virtual DbSet<MegrendelesTetel> MegrendelesTetel { get; set; }
        public virtual DbSet<Statusz> Statusz { get; set; }
        public virtual DbSet<Szamla> Szamla { get; set; }
        public virtual DbSet<SzamlaKiallito> SzamlaKiallito { get; set; }
        public virtual DbSet<SzamlaTetel> SzamlaTetel { get; set; }
        public virtual DbSet<Telephely> Telephely { get; set; }
        public virtual DbSet<Termek> Termek { get; set; }
        public virtual DbSet<Vevo> Vevo { get; set; }
    }
}
