//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nyivantarto
{
    using System;
    using System.Collections.Generic;
    
    public partial class SzamlaKiallito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SzamlaKiallito()
        {
            this.Szamla = new HashSet<Szamla>();
        }
    
        public int ID { get; set; }
        public string Nev { get; set; }
        public string IR { get; set; }
        public string Varos { get; set; }
        public string Utca { get; set; }
        public string Adoszam { get; set; }
        public string Szamlaszam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szamla> Szamla { get; set; }
    }
}
