//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nyivantarto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szamla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Szamla()
        {
            this.SzamlaTetel = new HashSet<SzamlaTetel>();
        }
    
        public int ID { get; set; }
        public string MegrendeloNev { get; set; }
        public string MegrendeloIR { get; set; }
        public string MegrendeloVaros { get; set; }
        public string MegrendeloUtca { get; set; }
        public Nullable<int> NyomtatottPeldanyszam { get; set; }
        public Nullable<bool> Sztorno { get; set; }
        public string FizetesiMod { get; set; }
        public Nullable<System.DateTime> KiallitasDatum { get; set; }
        public Nullable<System.DateTime> TeljesitesDatum { get; set; }
        public Nullable<System.DateTime> FizetesiHatarido { get; set; }
        public Nullable<int> KiallitoID { get; set; }
        public Nullable<int> MegrendelesID { get; set; }
    
        public virtual Megrendeles Megrendeles { get; set; }
        public virtual SzamlaKiallito SzamlaKiallito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SzamlaTetel> SzamlaTetel { get; set; }
    }
}
