//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nyivantarto
{
    using System;
    using System.Collections.Generic;
    
    public partial class SzamlaTetel
    {
        public int ID { get; set; }
        public string Nev { get; set; }
        public Nullable<int> Mennyiseg { get; set; }
        public Nullable<double> NettoAr { get; set; }
        public Nullable<int> SzamlaID { get; set; }
        public Nullable<int> MegrendelesTetelID { get; set; }
    
        public virtual MegrendelesTetel MegrendelesTetel { get; set; }
        public virtual Szamla Szamla { get; set; }
    }
}
