//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nyivantarto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Termek()
        {
            this.MegrendelesTetel = new HashSet<MegrendelesTetel>();
        }
    
        public int ID { get; set; }
        public string Nev { get; set; }
        public Nullable<double> NettoAr { get; set; }
        public Nullable<int> Raktarkeszlet { get; set; }
        public Nullable<int> AFAID { get; set; }
        public Nullable<int> KategoriaID { get; set; }
        public string Leiras { get; set; }
        public byte[] Kep { get; set; }
    
        public virtual AFA AFA { get; set; }
        public virtual Kategoria Kategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MegrendelesTetel> MegrendelesTetel { get; set; }
    }
}
